/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * IdentityExample API
 * OpenAPI spec version: v1
 */
import {
  HttpClient
} from '@angular/common/http';
import type {
  HttpContext,
  HttpEvent,
  HttpHeaders,
  HttpParams,
  HttpResponse as AngularHttpResponse
} from '@angular/common/http';

import {
  Injectable,
  inject
} from '@angular/core';

import {
  Observable
} from 'rxjs';

import type {
  IdentityRole,
  PostRoleCreate,
  PostRoleUpdate,
  PostUserClaimsRequest,
  PostUserRolesRequest,
  SignInRequest,
  SignUpRequest,
  UserClaimResponse,
  UserResponse
} from '../models';



interface HttpClientOptions {
  headers?: HttpHeaders | Record<string, string | string[]>;
  context?: HttpContext;
  params?:
        | HttpParams
        | Record<string, string | number | boolean | ReadonlyArray<string | number | boolean>>;
  reportProgress?: boolean;
  withCredentials?: boolean;
  credentials?: RequestCredentials;
  keepalive?: boolean;
  priority?: RequestPriority;
  cache?: RequestCache;
  mode?: RequestMode;
  redirect?: RequestRedirect;
  referrer?: string;
  integrity?: string;
  transferCache?: {includeHeaders?: string[]} | boolean;
  timeout?: number;
}



@Injectable({ providedIn: 'root' })
export class IdentityExampleAPIService {
  private readonly http = inject(HttpClient);
 postRegister<TData = void>(signUpRequest: SignUpRequest, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 postRegister<TData = void>(signUpRequest: SignUpRequest, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 postRegister<TData = void>(signUpRequest: SignUpRequest, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  postRegister<TData = void>(
    signUpRequest: SignUpRequest, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.post<TData>(
      `/register`,
      signUpRequest,options
    );
  }

 postLogin<TData = void>(signInRequest: SignInRequest, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 postLogin<TData = void>(signInRequest: SignInRequest, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 postLogin<TData = void>(signInRequest: SignInRequest, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  postLogin<TData = void>(
    signInRequest: SignInRequest, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.post<TData>(
      `/login`,
      signInRequest,options
    );
  }

 postLogout<TData = void>( options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 postLogout<TData = void>( options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 postLogout<TData = void>( options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  postLogout<TData = void>(
     options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.post<TData>(
      `/logout`,undefined,options
    );
  }

 getUser<TData = void>( options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 getUser<TData = void>( options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 getUser<TData = void>( options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  getUser<TData = void>(
     options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.get<TData>(
      `/user`,options
    );
  }

 getUsers<TData = UserResponse[]>( options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 getUsers<TData = UserResponse[]>( options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 getUsers<TData = UserResponse[]>( options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  getUsers<TData = UserResponse[]>(
     options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.get<TData>(
      `/users`,options
    );
  }

 getUsersUserIdClaims<TData = UserClaimResponse[]>(userId: string, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 getUsersUserIdClaims<TData = UserClaimResponse[]>(userId: string, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 getUsersUserIdClaims<TData = UserClaimResponse[]>(userId: string, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  getUsersUserIdClaims<TData = UserClaimResponse[]>(
    userId: string, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.get<TData>(
      `/users/${userId}/claims`,options
    );
  }

 postUsersUserIdClaims<TData = void>(userId: string,
    postUserClaimsRequest: PostUserClaimsRequest, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 postUsersUserIdClaims<TData = void>(userId: string,
    postUserClaimsRequest: PostUserClaimsRequest, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 postUsersUserIdClaims<TData = void>(userId: string,
    postUserClaimsRequest: PostUserClaimsRequest, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  postUsersUserIdClaims<TData = void>(
    userId: string,
    postUserClaimsRequest: PostUserClaimsRequest, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.post<TData>(
      `/users/${userId}/claims`,
      postUserClaimsRequest,options
    );
  }

 getClaims<TData = void>( options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 getClaims<TData = void>( options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 getClaims<TData = void>( options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  getClaims<TData = void>(
     options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.get<TData>(
      `/claims`,options
    );
  }

 getRoles<TData = void>( options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 getRoles<TData = void>( options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 getRoles<TData = void>( options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  getRoles<TData = void>(
     options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.get<TData>(
      `/roles`,options
    );
  }

 postRoles<TData = IdentityRole>(postRoleCreate: PostRoleCreate, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 postRoles<TData = IdentityRole>(postRoleCreate: PostRoleCreate, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 postRoles<TData = IdentityRole>(postRoleCreate: PostRoleCreate, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  postRoles<TData = IdentityRole>(
    postRoleCreate: PostRoleCreate, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.post<TData>(
      `/roles`,
      postRoleCreate,options
    );
  }

 postRolesRoleId<TData = void>(roleId: string,
    postRoleUpdate: PostRoleUpdate, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 postRolesRoleId<TData = void>(roleId: string,
    postRoleUpdate: PostRoleUpdate, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 postRolesRoleId<TData = void>(roleId: string,
    postRoleUpdate: PostRoleUpdate, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  postRolesRoleId<TData = void>(
    roleId: string,
    postRoleUpdate: PostRoleUpdate, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.post<TData>(
      `/roles/${roleId}`,
      postRoleUpdate,options
    );
  }

 getUsersUserIdRoles<TData = void>(userId: string, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 getUsersUserIdRoles<TData = void>(userId: string, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 getUsersUserIdRoles<TData = void>(userId: string, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  getUsersUserIdRoles<TData = void>(
    userId: string, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.get<TData>(
      `/users/${userId}/roles`,options
    );
  }

 postUsersUserIdRoles<TData = void>(userId: string,
    postUserRolesRequest: PostUserRolesRequest, options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
 postUsersUserIdRoles<TData = void>(userId: string,
    postUserRolesRequest: PostUserRolesRequest, options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
 postUsersUserIdRoles<TData = void>(userId: string,
    postUserRolesRequest: PostUserRolesRequest, options?: HttpClientOptions & { observe: 'response' }): Observable<AngularHttpResponse<TData>>;
  postUsersUserIdRoles<TData = void>(
    userId: string,
    postUserRolesRequest: PostUserRolesRequest, options?: HttpClientOptions & { observe?: any }): Observable<any> {
    return this.http.post<TData>(
      `/users/${userId}/roles`,
      postUserRolesRequest,options
    );
  }

};

export type PostRegisterClientResult = NonNullable<void>
export type PostLoginClientResult = NonNullable<void>
export type PostLogoutClientResult = NonNullable<void>
export type GetUserClientResult = NonNullable<void>
export type GetUsersClientResult = NonNullable<UserResponse[]>
export type GetUsersUserIdClaimsClientResult = NonNullable<UserClaimResponse[]>
export type PostUsersUserIdClaimsClientResult = NonNullable<void>
export type GetClaimsClientResult = NonNullable<void>
export type GetRolesClientResult = NonNullable<void>
export type PostRolesClientResult = NonNullable<IdentityRole>
export type PostRolesRoleIdClientResult = NonNullable<void>
export type GetUsersUserIdRolesClientResult = NonNullable<void>
export type PostUsersUserIdRolesClientResult = NonNullable<void>
