/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * IdentityExample API
 * OpenAPI spec version: v1
 */
import type {
  SignInRequest,
  SignUpRequest
} from '../models';


export type postRegisterResponse200 = {
  data: void
  status: 200
}

export type postRegisterResponse400 = {
  data: string[]
  status: 400
}
    
export type postRegisterResponseSuccess = (postRegisterResponse200) & {
  headers: Headers;
};
export type postRegisterResponseError = (postRegisterResponse400) & {
  headers: Headers;
};

export type postRegisterResponse = (postRegisterResponseSuccess | postRegisterResponseError)

export const getPostRegisterUrl = () => {


  

  return `https://localhost:7142/register`
}

export const postRegister = async (signUpRequest: SignUpRequest, options?: RequestInit): Promise<postRegisterResponse> => {
  
  const res = await fetch(getPostRegisterUrl(),
  {
      credentials: 'include',
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      signUpRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postRegisterResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postRegisterResponse
}



export type postLoginResponse200 = {
  data: void
  status: 200
}

export type postLoginResponse401 = {
  data: void
  status: 401
}
    
export type postLoginResponseSuccess = (postLoginResponse200) & {
  headers: Headers;
};
export type postLoginResponseError = (postLoginResponse401) & {
  headers: Headers;
};

export type postLoginResponse = (postLoginResponseSuccess | postLoginResponseError)

export const getPostLoginUrl = () => {


  

  return `https://localhost:7142/login`
}

export const postLogin = async (signInRequest: SignInRequest, options?: RequestInit): Promise<postLoginResponse> => {
  
  const res = await fetch(getPostLoginUrl(),
  {
      credentials: 'include',
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      signInRequest,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postLoginResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postLoginResponse
}



export type postLogoutResponse200 = {
  data: void
  status: 200
}
    
export type postLogoutResponseSuccess = (postLogoutResponse200) & {
  headers: Headers;
};
;

export type postLogoutResponse = (postLogoutResponseSuccess)

export const getPostLogoutUrl = () => {


  

  return `https://localhost:7142/logout`
}

export const postLogout = async ( options?: RequestInit): Promise<postLogoutResponse> => {
  
  const res = await fetch(getPostLogoutUrl(),
  {
      credentials: 'include',
    ...options,
    method: 'POST'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: postLogoutResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postLogoutResponse
}



export type getUserResponse200 = {
  data: void
  status: 200
}
    
export type getUserResponseSuccess = (getUserResponse200) & {
  headers: Headers;
};
;

export type getUserResponse = (getUserResponseSuccess)

export const getGetUserUrl = () => {


  

  return `https://localhost:7142/user`
}

export const getUser = async ( options?: RequestInit): Promise<getUserResponse> => {
  
  const res = await fetch(getGetUserUrl(),
  {
      credentials: 'include',
    ...options,
    method: 'GET'
    
    
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: getUserResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getUserResponse
}



