/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * IdentityExample API
 * OpenAPI spec version: v1
 */

export interface IdentityRole {
  /** @nullable */
  id?: string | null;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  normalizedName?: string | null;
  /** @nullable */
  concurrencyStamp?: string | null;
}
