/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * IdentityExample API
 * OpenAPI spec version: v1
 */

export interface SignUpRequest {
  /** @nullable */
  email?: string | null;
  /** @nullable */
  password?: string | null;
}
