/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * IdentityExample API
 * OpenAPI spec version: v1
 */

export interface UserClaimResponse {
  id?: number;
  /** @nullable */
  value?: string | null;
}
