/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * IdentityExample API
 * OpenAPI spec version: v1
 */

export interface UserResponse {
  /** @nullable */
  id?: string | null;
  /** @nullable */
  userName?: string | null;
  /** @nullable */
  email?: string | null;
}
